name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PP_TOKEN }}
          user: assirims
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Riyadh
          plugin_traffic: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_stars: yes
          plugin_stars_limit: 1          
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic          
          plugin_repositories: yes
          plugin_repositories_pinned: 2          
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1          
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8         
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_followup: yes
          plugin_followup_archived: no      
          plugin_calendar: yes
          plugin_calendar_limit: 2          
          plugin_activity: yes
          plugin_activity_limit: 1
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create          
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
